# Site settings
title: Осирисын хувийн блог
description: > # this means to ignore newlines until "baseurl:"
  Програм хангамжийн инженер мэргэжлээр суралцагч оюутан бөгөөд
  вэб, мобайл програмчлал болон системийн аюулгүй байдал сонирхдог.
url: https://enkhee-Osiris.github.io # the base hostname & protocol for your site
author:
  name: Энхээ Осирис
  email: enkhee.ag@gmail.com
  youtube: UCJiAzkHY50R8TU6XPgbS8tg
  tumblr: lodrosiris
  github: enkhee-Osiris
  facebook: Ag.Enkhee
  facebook_id: 100003629098903
  instagram: osiris.ag
  google_plus: enkhee-Osiris
  feedburner: feedname

lang: mn_MN

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

# Handling Reading
exclude: [Gemfile, README.md]

# Plugins
plugins:
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag


# Outputting
permalink: /:categories/:year/:month/:day/:title
timezone: Asia/Ulaanbaatar

# assets
BASE_PATH: false
ASSET_PATH: false

# Defaults
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag


# Settings for comments
comments:
  facebook:
    appid: 1184490104906355
    num_posts: 5
    width: 580
    colorscheme: light

# Settings for analytics helper
analytics:
  google:
    tracking_id: 'UA-80597159-1'

# Build settings
markdown: kramdown

# Some static texts
text:
  minute_read: минут уншина.
  less_than_minute_read: Минут хүрэхгүй.
